name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: lein deps
      - name: Run tests
        run: lein test
      - name: Create Jars
        run: lein uberjar
      - name: Deploy to Clojars
        run: lein deploy clojars
        env:
          CLOJARS_AUTH: ${{ secrets.CLOJARS_USERNAME }}:${{ secrets.CLOJARS_API_KEY }}
